### ISSUE TITLE
Indonesian Translation Progress Checklist

### ISSUE THREAD

**Issue by ululamri** [solidity-docs/id-indonesian#2]
## Translation Progress Checklist

This document helps to track the state of your translation. Please copy it as an issue into your translation repo to track your progress.

### Maintainer List

@ululamri
@trocok 

### Information for New Translators

To translate a page:

Check that no one else has claimed your page in the checklist and comments below.
Comment below with the name of the page you would like to translate. Please take only one page at a time.
Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (link them here if they exist) to understand how to translate various technical or Solidity/Ethereum-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

### For Maintainers

When someone likes to contribute, edit this issue with the username of the contributor, and with the PR. 

E.g. 
- [ ] index (@franzihei) #1

When PRs are merged, make sure to mark that page as completed.

### Core Pages

These pages need to be translated before the translation will be added as a new language to the Solidity docs flyout menu. Please translate these pages first. 

#### Basics
- [x] index
- [x] intro-to-smart-contracts
- [x] installing-solidity
- [x] solidity-by-example

#### Language Description
- [x] layout-of-source-files
- [x] structure-of-a-contract
- [x] types
- [x] units-and-global-variables
- [x] control-structures
- [x] contracts
- [x] assembly
- [x] cheatsheet
- [x] grammar

#### Internals
- [x] layout_in_storage
- [x] layout_in_memory
- [x] layout_in_calldata
- [x] variable_cleanup
- [x] source_mappings
- [x] optimiser
- [x] metadata
- [x] abi-spec

#### Additional Material
- [x] yul
- [x] natspec-format
- [x] security-considerations
- [x] common-patterns

### Next Steps

These are the next most important translations, ordered by importance:

#### Additional Material

- [x] using-the-compiler
- [x] contributing
- [x] 080-breaking-changes
- [x] 070-breaking-changes
- [x] 060-breaking-changes
- [x] 050-breaking-changes
- [x] resources
- [x] bugs

### Additional Translations

These are not the primary translation targets but still a nice to have!

- [x] style-guide
- [x] brand-guide

_Credits: This doc is derived from the [Progress Template](https://github.com/reactjs/reactjs.org-translation/blob/master/PROGRESS.template.md) of the ReactJS Localization Team._
